apiVersion: apps/v1
kind: Deployment
metadata:
  name: numerical-app
  labels:
    app: numerical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: numerical
  template:
    metadata:
      labels:
        app: numerical
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
        - image: harbor.arpansahu.me/library/numerical:latest
          name: numerical
          envFrom:
            - secretRef:
                name: arpansahu-dot-me-secret
          ports:
            - containerPort: 8003
              name: gunicorn