apiVersion: v1
kind: Service
metadata:
  name: numerical-service
spec:
  selector:
    app: numerical
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
      nodePort: 32003
  type: NodePort