apiVersion: v1
kind: Service
metadata:
  name: numerical-service
spec:
  selector:
    app: numerical
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32000
  type: NodePort